.\" Manpage do @nome_do_script@

.TH man 1 "@data@" "1.0" "@nome_do_script@ man page"

.SH NAME
@nome_do_script@ \- TODO....

.SH SYNOPSIS
.B @nome_do_script@
[PARAM]

.B @nome_do_script@
[param1] [param2]

.SH DESCRIPTION
TODO...

.B FUNCIONALITIES
.RS
1. TODO...

2. TODO...

3. TODO...

.SH OPTIONS
.B -h | --help
 \- Mostra ajuda do comando

.B param1
\- TODO...

.B param2
\- TODO...

.SH BUGS
Bug Report pode enviar para <@email@>

.SH DEPENDENCIES
.B app
 \- ferramenta que TODO....

.SH AUTHOR
@autor@ (@email@) para correção de bug, dúvidas, sugestões e café =D.

.SH EXAMPLES
.B @nome_do_script@ "param1" "param2"
.RS
Execução normal do comando

.RE
.B @nome_do_script@ --help
.RS
Página de ajuda do comando
